// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Treasury.Infrastructure.Persistence;

#nullable disable

namespace Treasury.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TreasuryDbContext))]
    [Migration("20260713101802_AddTreasuryAlerts")]
    partial class AddTreasuryAlerts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Treasury.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AccountTypeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ReservedBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.HasIndex("AccountTypeId");

                    b.ToTable("Accounts", t =>
                        {
                            t.HasCheckConstraint("CK_Accounts_Balance_NonNegative", "\"Balance\" >= 0");

                            t.HasCheckConstraint("CK_Accounts_Currency_Length", "char_length(\"Currency\") = 3");

                            t.HasCheckConstraint("CK_Accounts_ReservedBalance_NonNegative", "\"ReservedBalance\" >= 0");

                            t.HasCheckConstraint("CK_Accounts_ReservedBalance_NotAboveBalance", "\"ReservedBalance\" <= \"Balance\"");
                        });
                });

            modelBuilder.Entity("Treasury.Domain.Entities.AccountType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AccountTypes");
                });

            modelBuilder.Entity("Treasury.Domain.Entities.ApprovalDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApproverUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PaymentRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReversalRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TransferRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApproverUserId");

                    b.HasIndex("PaymentRequestId", "ApproverUserId")
                        .IsUnique();

                    b.HasIndex("ReversalRequestId", "ApproverUserId")
                        .IsUnique();

                    b.HasIndex("TransferRequestId", "ApproverUserId")
                        .IsUnique();

                    b.ToTable("ApprovalDecisions", t =>
                        {
                            t.HasCheckConstraint("CK_ApprovalDecisions_Decision", "\"Decision\" IN ('Approved', 'Rejected')");

                            t.HasCheckConstraint("CK_ApprovalDecisions_OneRequest", "num_nonnulls(\"TransferRequestId\", \"PaymentRequestId\", \"ReversalRequestId\") = 1");
                        });
                });

            modelBuilder.Entity("Treasury.Domain.Entities.ApprovalPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PendingRequestExpiryHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(24);

                    b.Property<int>("RequiredApprovalCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<decimal>("ThresholdAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("OperationType", "Currency")
                        .IsUnique();

                    b.ToTable("ApprovalPolicies", t =>
                        {
                            t.HasCheckConstraint("CK_ApprovalPolicies_Currency", "char_length(\"Currency\") = 3");

                            t.HasCheckConstraint("CK_ApprovalPolicies_OperationType", "\"OperationType\" IN ('InternalTransfer', 'CashPayment', 'TransactionReversal')");

                            t.HasCheckConstraint("CK_ApprovalPolicies_PendingRequestExpiryHours", "\"PendingRequestExpiryHours\" BETWEEN 1 AND 168");

                            t.HasCheckConstraint("CK_ApprovalPolicies_RequiredApprovalCount", "\"RequiredApprovalCount\" BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_ApprovalPolicies_Threshold", "\"ThresholdAmount\" >= 0");
                        });
                });

            modelBuilder.Entity("Treasury.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ActorEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ActorRole")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AfterValuesJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("BeforeValuesJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("ActorUserId", "OccurredAtUtc");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs", t =>
                        {
                            t.HasCheckConstraint("CK_AuditLogs_Action", "\"Action\" IN ('Created','Updated','Deleted','Approved','Rejected','Resolved','Dismissed','Cancelled','Realized','Matched','Reconciled','Ignored','Expired','Imported','LoggedIn','RoleChanged')");

                            t.HasCheckConstraint("CK_AuditLogs_EntityType", "\"EntityType\" IN ('User','Role','Account','AccountType','TransferRequest','PaymentRequest','ReversalRequest','ApprovalPolicy','ApprovalDecision','TreasuryTransaction','BankStatementImport','BankStatementLine','CashFlowForecastItem','FxRate','TreasuryAlert','System')");
                        });
                });

            modelBuilder.Entity("Treasury.Domain.Entities.BankStatementImport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ClosingBalance")
                        .HasColumnType("numeric");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("LineCount")
                        .HasColumnType("integer");

                    b.Property<decimal?>("OpeningBalance")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("StatementFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StatementReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("StatementToUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UploadedAtUtc");

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("AccountId", "StatementReference");

                    b.ToTable("BankStatementImports", t =>
                        {
                            t.HasCheckConstraint("CK_BankStatementImports_Currency_Length", "char_length(\"Currency\") = 3");

                            t.HasCheckConstraint("CK_BankStatementImports_LineCount", "\"LineCount\" >= 0");
                        });
                });

            modelBuilder.Entity("Treasury.Domain.Entities.BankStatementLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BalanceAfterTransaction")
                        .HasColumnType("numeric");

                    b.Property<string>("BankReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("BankStatementImportId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CounterpartyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("MatchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MatchedTreasuryTransactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReconciledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReconciledByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReconciliationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TransactionDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValueDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MatchedTreasuryTransactionId");

                    b.HasIndex("ReconciledByUserId");

                    b.HasIndex("BankStatementImportId", "LineNumber")
                        .IsUnique();

                    b.HasIndex("AccountId", "ReconciliationStatus", "TransactionDateUtc");

                    b.ToTable("BankStatementLines", t =>
                        {
                            t.HasCheckConstraint("CK_BankStatementLines_Amount_NotZero", "\"Amount\" <> 0");

                            t.HasCheckConstraint("CK_BankStatementLines_Currency_Length", "char_length(\"Currency\") = 3");

                            t.HasCheckConstraint("CK_BankStatementLines_LineNumber", "\"LineNumber\" > 0");

                            t.HasCheckConstraint("CK_BankStatementLines_ReconciliationStatus", "\"ReconciliationStatus\" IN ('Unmatched', 'Matched', 'Reconciled', 'Ignored')");
                        });
                });

            modelBuilder.Entity("Treasury.Domain.Entities.CashFlowForecastItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CancelledByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CounterpartyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("ExpectedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RealizedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RealizedTreasuryTransactionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CancelledByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("RealizedTreasuryTransactionId")
                        .IsUnique();

                    b.HasIndex("AccountId", "Status", "ExpectedDateUtc");

                    b.HasIndex("Currency", "Status", "ExpectedDateUtc");

                    b.ToTable("CashFlowForecastItems", t =>
                        {
                            t.HasCheckConstraint("CK_CashFlowForecastItems_Amount_Positive", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_CashFlowForecastItems_Currency_Length", "char_length(\"Currency\") = 3");

                            t.HasCheckConstraint("CK_CashFlowForecastItems_Direction", "\"Direction\" IN ('Inflow', 'Outflow')");

                            t.HasCheckConstraint("CK_CashFlowForecastItems_SourceType", "\"SourceType\" IN ('Manual', 'CustomerReceipt', 'SupplierPayment', 'Payroll', 'Tax', 'Loan', 'Investment', 'Other')");

                            t.HasCheckConstraint("CK_CashFlowForecastItems_Status", "\"Status\" IN ('Active', 'Cancelled', 'Realized')");
                        });
                });

            modelBuilder.Entity("Treasury.Domain.Entities.FxRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("RateDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ToCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ToCurrency", "RateDateUtc");

                    b.HasIndex("FromCurrency", "ToCurrency", "RateDateUtc")
                        .IsUnique();

                    b.ToTable("FxRates", t =>
                        {
                            t.HasCheckConstraint("CK_FxRates_DifferentCurrencies", "\"FromCurrency\" <> \"ToCurrency\"");

                            t.HasCheckConstraint("CK_FxRates_FromCurrency_Length", "char_length(\"FromCurrency\") = 3");

                            t.HasCheckConstraint("CK_FxRates_Rate_Positive", "\"Rate\" > 0");

                            t.HasCheckConstraint("CK_FxRates_SourceType", "\"SourceType\" IN ('Manual', 'CentralBank', 'Bank', 'Market', 'Other')");

                            t.HasCheckConstraint("CK_FxRates_ToCurrency_Length", "char_length(\"ToCurrency\") = 3");
                        });
                });

            modelBuilder.Entity("Treasury.Domain.Entities.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TreasuryTransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("TreasuryTransactionId");

                    b.ToTable("LedgerEntries", t =>
                        {
                            t.HasCheckConstraint("CK_LedgerEntries_Amount_Positive", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_LedgerEntries_EntryType", "\"EntryType\" IN ('Debit', 'Credit')");
                        });
                });

            modelBuilder.Entity("Treasury.Domain.Entities.PaymentRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("ApprovalCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("BeneficiaryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalReference")
                        .HasColumnType("text");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("RequiredApprovalCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "ExpiresAtUtc");

                    b.ToTable("PaymentRequests", t =>
                        {
                            t.HasCheckConstraint("CK_PaymentRequests_Amount_Positive", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_PaymentRequests_ApprovalCounts", "\"RequiredApprovalCount\" >= 1 AND \"ApprovalCount\" >= 0 AND \"ApprovalCount\" <= \"RequiredApprovalCount\"");

                            t.HasCheckConstraint("CK_PaymentRequests_Status", "\"Status\" IN ('Pending', 'Approved', 'Rejected', 'Expired')");
                        });
                });

            modelBuilder.Entity("Treasury.Domain.Entities.ReversalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ApprovalCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OriginalTransactionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("RequiredApprovalCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OriginalTransactionId")
                        .IsUnique();

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "ExpiresAtUtc");

                    b.ToTable("ReversalRequests", t =>
                        {
                            t.HasCheckConstraint("CK_ReversalRequests_ApprovalCounts", "\"RequiredApprovalCount\" >= 1 AND \"ApprovalCount\" >= 0 AND \"ApprovalCount\" <= \"RequiredApprovalCount\"");

                            t.HasCheckConstraint("CK_ReversalRequests_Status", "\"Status\" IN ('Pending', 'Approved', 'Rejected', 'Expired')");
                        });
                });

            modelBuilder.Entity("Treasury.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Treasury.Domain.Entities.TransferRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("ApprovalCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FromAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("RequiredApprovalCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ToAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "ExpiresAtUtc");

                    b.ToTable("TransferRequests", t =>
                        {
                            t.HasCheckConstraint("CK_TransferRequests_Amount_Positive", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_TransferRequests_ApprovalCounts", "\"RequiredApprovalCount\" >= 1 AND \"ApprovalCount\" >= 0 AND \"ApprovalCount\" <= \"RequiredApprovalCount\"");

                            t.HasCheckConstraint("CK_TransferRequests_Status", "\"Status\" IN ('Pending', 'Approved', 'Rejected', 'Expired')");
                        });
                });

            modelBuilder.Entity("Treasury.Domain.Entities.TreasuryAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ClosedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClosureNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("SourceEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceEntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceModule")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ClosedByUserId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("AlertType", "Status");

                    b.HasIndex("SourceEntityType", "SourceEntityId");

                    b.HasIndex("Status", "Severity");

                    b.ToTable("TreasuryAlerts", t =>
                        {
                            t.HasCheckConstraint("CK_TreasuryAlerts_AlertType", "\"AlertType\" IN ('LowLiquidity', 'ForecastLiquidityGap', 'PendingApproval', 'ReconciliationException', 'FxExposure', 'AuditException', 'System')");

                            t.HasCheckConstraint("CK_TreasuryAlerts_Currency_Length", "\"Currency\" IS NULL OR char_length(\"Currency\") = 3");

                            t.HasCheckConstraint("CK_TreasuryAlerts_Severity", "\"Severity\" IN ('Info', 'Warning', 'Critical')");

                            t.HasCheckConstraint("CK_TreasuryAlerts_Status", "\"Status\" IN ('Open', 'Resolved', 'Dismissed')");
                        });
                });

            modelBuilder.Entity("Treasury.Domain.Entities.TreasuryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CompletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CounterpartyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("DestinationAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("InitiatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PaymentRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ReversalRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReversesTransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TransferRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompletedByUserId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("DestinationAccountId");

                    b.HasIndex("ExternalReference");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("InitiatedByUserId");

                    b.HasIndex("PaymentRequestId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("ReversalRequestId");

                    b.HasIndex("ReversesTransactionId")
                        .IsUnique();

                    b.HasIndex("SourceAccountId");

                    b.HasIndex("TransferRequestId");

                    b.ToTable("TreasuryTransactions", t =>
                        {
                            t.HasCheckConstraint("CK_TreasuryTransactions_Amount_Positive", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_TreasuryTransactions_Currency_Length", "char_length(\"Currency\") = 3");

                            t.HasCheckConstraint("CK_TreasuryTransactions_Status", "\"Status\" IN ('Completed')");
                        });
                });

            modelBuilder.Entity("Treasury.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Treasury.Domain.Entities.Account", b =>
                {
                    b.HasOne("Treasury.Domain.Entities.AccountType", "AccountType")
                        .WithMany("Accounts")
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountType");
                });

            modelBuilder.Entity("Treasury.Domain.Entities.ApprovalDecision", b =>
                {
                    b.HasOne("Treasury.Domain.Entities.User", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Treasury.Domain.Entities.PaymentRequest", null)
                        .WithMany()
                        .HasForeignKey("PaymentRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Treasury.Domain.Entities.ReversalRequest", null)
                        .WithMany()
                        .HasForeignKey("ReversalRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Treasury.Domain.Entities.TransferRequest", null)
                        .WithMany()
                        .HasForeignKey("TransferRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Approver");
                });

            modelBuilder.Entity("Treasury.Domain.Entities.ApprovalPolicy", b =>
                {
                    b.HasOne("Treasury.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Treasury.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("Treasury.Domain.Entities.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("Treasury.Domain.Entities.BankStatementImport", b =>
                {
                    b.HasOne("Treasury.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Treasury.Domain.Entities.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("Treasury.Domain.Entities.BankStatementLine", b =>
                {
                    b.HasOne("Treasury.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Treasury.Domain.Entities.BankStatementImport", "BankStatementImport")
                        .WithMany("Lines")
                        .HasForeignKey("BankStatementImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Treasury.Domain.Entities.TreasuryTransaction", "MatchedTreasuryTransaction")
                        .WithMany()
                        .HasForeignKey("MatchedTreasuryTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Treasury.Domain.Entities.User", "ReconciledByUser")
                        .WithMany()
                        .HasForeignKey("ReconciledByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("BankStatementImport");

                    b.Navigation("MatchedTreasuryTransaction");

                    b.Navigation("ReconciledByUser");
                });

            modelBuilder.Entity("Treasury.Domain.Entities.CashFlowForecastItem", b =>
                {
                    b.HasOne("Treasury.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Treasury.Domain.Entities.User", "CancelledByUser")
                        .WithMany()
                        .HasForeignKey("CancelledByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Treasury.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Treasury.Domain.Entities.TreasuryTransaction", "RealizedTreasuryTransaction")
                        .WithMany()
                        .HasForeignKey("RealizedTreasuryTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("CancelledByUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("RealizedTreasuryTransaction");
                });

            modelBuilder.Entity("Treasury.Domain.Entities.FxRate", b =>
                {
                    b.HasOne("Treasury.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Treasury.Domain.Entities.LedgerEntry", b =>
                {
                    b.HasOne("Treasury.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Treasury.Domain.Entities.TreasuryTransaction", "TreasuryTransaction")
                        .WithMany("LedgerEntries")
                        .HasForeignKey("TreasuryTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("TreasuryTransaction");
                });

            modelBuilder.Entity("Treasury.Domain.Entities.PaymentRequest", b =>
                {
                    b.HasOne("Treasury.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Treasury.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Treasury.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Treasury.Domain.Entities.ReversalRequest", b =>
                {
                    b.HasOne("Treasury.Domain.Entities.TreasuryTransaction", "OriginalTransaction")
                        .WithMany()
                        .HasForeignKey("OriginalTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Treasury.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Treasury.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OriginalTransaction");
                });

            modelBuilder.Entity("Treasury.Domain.Entities.TreasuryAlert", b =>
                {
                    b.HasOne("Treasury.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Treasury.Domain.Entities.User", "ClosedByUser")
                        .WithMany()
                        .HasForeignKey("ClosedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Treasury.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("ClosedByUser");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Treasury.Domain.Entities.TreasuryTransaction", b =>
                {
                    b.HasOne("Treasury.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CompletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Treasury.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("DestinationAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Treasury.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("InitiatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Treasury.Domain.Entities.PaymentRequest", null)
                        .WithMany()
                        .HasForeignKey("PaymentRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Treasury.Domain.Entities.ReversalRequest", null)
                        .WithMany()
                        .HasForeignKey("ReversalRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Treasury.Domain.Entities.TreasuryTransaction", "ReversesTransaction")
                        .WithMany()
                        .HasForeignKey("ReversesTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Treasury.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("SourceAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Treasury.Domain.Entities.TransferRequest", null)
                        .WithMany()
                        .HasForeignKey("TransferRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ReversesTransaction");
                });

            modelBuilder.Entity("Treasury.Domain.Entities.User", b =>
                {
                    b.HasOne("Treasury.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Treasury.Domain.Entities.AccountType", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Treasury.Domain.Entities.BankStatementImport", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Treasury.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Treasury.Domain.Entities.TreasuryTransaction", b =>
                {
                    b.Navigation("LedgerEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
